title: watchmetrain
url: http://watchmetrain.net
keywords:
 - Mike Griffin
 - Michael Griffin

permalink: /blog/:year:month:day-:title

author:
    name: Mike Griffin
    email: griffinm@gmail.com

exclude:
 - Rakefile
 - README.markdown
 - .git
