source "https://rubygems.org"
gem 'sinatra'
gem 'RedCloth'
gem 'xml-sitemap'
gem 'sequel'
gem 'sqlite3'
gem 'haml'
gem 'chronic'
gem 'chronic_duration'
gem 'chronic_distance'
gem 'scruffy'
gem 'builder', '>= 2.0'
gem 'mysql'
