source :rubygems
gem 'sinatra', '=1.0'
gem 'RedCloth'
gem 'rack-flash'
gem 'xml-sitemap'
gem 'sequel'
gem 'sqlite3'
gem 'haml'
gem 'chronic'
gem 'chronic_duration'
gem 'chronic_distance'
gem 'scruffy'
gem 'builder', '>= 2.0'
gem 'mysql'